### ISSUE TITLE
Courses parser doesn't appear to be pulling data for UTSG

### ISSUE THREAD

**Issue by bill-ahmed** [nikel-api/nikel-parser#2]
When running the Courses parser (`courses.py`), I noticed that the output JSON does not include any data for UTSG courses.

**Reproduction Steps**
1. Run courses parser `python courses.py`
2. Open `courses.json` under `data` folder

**Expected Result**
There exists course data for UTSG

**Actual Result**
Not course data found.

**Additional Info**
I've attached a minified-zip of a JSON response given by querying the following via GET: `https://timetable.iit.artsci.utoronto.ca/api/20209/courses?org=&code=&section=F&studyyear=&daytime=&weekday=&prof=&breadth=&deliverymode=&waitlist=&available=&title=`

[UTSG_Courses.zip](https://github.com/nikel-api/nikel-parser/files/4900120/courses_2.zip)

**Comment by darenliang** [comment]
Is the `courses.json` file completely empty or is there data in it?

Could you provide a zip file containing `courses.json`?

**Comment by bill-ahmed** [comment]
The `courses.json` file already had data in it. Here's what I got after running the parser once: 

[courses.zip](https://github.com/nikel-api/nikel-parser/files/4900138/courses.zip)

**Comment by darenliang** [comment]
You are correct. UTSG courses are not showing up.

When I last populated the dataset, UTSG courses seemed to show up, which makes this extra weird.

Apparently changing `http` to `https` fixes the problem on my side. Could be that when I ran the code earlier, the `http` request got upgraded to a `https` request?

Not entirely sure.

This commit attempts to fix this problem: 2355abbe414d0b9a874940417845c31f808d5a65

**Comment by bill-ahmed** [comment]
Confirmed to be working after changed to `https`!
