### ISSUE TITLE
Scripts might be broken

### ISSUE THREAD

**Issue by darenliang** [nikel-api/nikel-parser#8]
After the change referenced in #7, the datasets are now located in a different repo.

This might break the cron jobs located in the scripts folder and maybe some minor changes might be necessary.

**Comment by bill-ahmed** [comment]
Yep looks like it'll need to pull down the submodule and update the paths to the data files.

**Comment by darenliang** [comment]
Oh ok. I guess it just needs some minor changes to commit from the right repo.

**Comment by bill-ahmed** [comment]
Created a PR to address it ^
